### ISSUE TITLE
ctags are not generated for perl .cgi files

### ISSUE THREAD

**Issue by nserrano10** [henriiik/vscode-perl#19]
Hi Henri:
  I have installed your extension (and ctags) and i opened a perl .cgi file. I have set the language of this file to Perl and all code is color coded correctly. The problem is that no ctags are generated for cgi file so symbol navigation doesnt work. Everything works ok for .pl and .pm files. Can you help figure out whats going on?

**Comment by pkggit** [comment]
The problem is with ctags which doesn't see .cgi as a perl file.
You can add this by adding --langmap=perl:.cgi to the ctags parameters

**Comment by ngetahun** [comment]
@pkggit Cool, is it possible for you to make a PR? I can merge it afterwards

**Comment by pkggit** [comment]
Still having issues :(
The .vstags file is containing the tags. but the outline doesn't show them.

**Comment by ngetahun** [comment]
There's a new version of this extension with support to the Outline API. Perhaps you can install that in your local vscode extensions directory and try it. Let me know if it still doesn't work

**Comment by pkggit** [comment]
My version was already at 1.18. So this version doesn't solve this issue.

**Comment by ngetahun** [comment]
Okay, good catch, could you create an issue for that? Thank you 🙂

**Comment by pkggit** [comment]
Perhaps I was wrong...I tested with a "normal" perl file. I do get the outline, but there are no tags in the .vstags file.

Is the .vstags file still being used?

**Comment by ngetahun** [comment]
Yes, perhaps you can generate it again with `cmd` + `shift` + `p` (`ctrl` + `shift` + `p` on windows) and typing `perl`.

**Comment by nserrano10** [comment]
How can i manually install 1.18 so i can test with my code?

**Comment by ngetahun** [comment]
I just pushed version 1.18 packaged, you can install it by first cloning this repo or fetching from master and then running the command to install from vsix found [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

**Comment by nserrano10** [comment]
Just installed 1.18 and still get "No symbols...." message for cgi files.

**Comment by ngetahun** [comment]
@nserrano10 Can you create an issue for this?
